### ISSUE TITLE
Can this library receive events from a server?

### ISSUE THREAD

**Issue by abhijeetbhagat** [kchmck/uhttp_sse.rs#1]
Hello! I am implementing a [SignalR](https://www.asp.net/signalr) client [library](https://github.com/abhijeetbhagat/genmei) and i was wondering if i can use this library to subscribe to streaming from a server.

Thanks!

**Comment by kchmck** [comment]
Hey @abhijeetbhagat, unfortunately this library only supports the generation of SSE messages and doesn't implement any of the receiving/decoding logic. That side of things would likely be better off as a new crate.
